CHUNK_SIZE = 1024
OVERLAP_RATIO = 0.2

TOP_K = 20
MAX_CHUNKS_PER_TALK = 3

BATCH_SIZE_SMALL = 20
BATCH_SIZE = 100

SMALL_CSV_PATH = "data/ted_talks_en-small.csv"
BIG_CSV_PATH = "data/ted_talks_en.csv"

LEN_SMALL_CSV = 5